worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    
    upstream node_backend {
        # Round Robin está activo por defecto en Nginx
        server backend1:8081;
        server backend2:8082;
        server backend3:8083;
    }

    server {
        listen 80;
        server_name localhost;

        # Sirve el Frontend estático
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Redirige peticiones /api/ hacia el cluster de Backends
        location /api/ {
            proxy_pass http://node_backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
